export interface XhsImage {
  id: string;
  url: string; // The original URL
  previewUrl: string; // Smaller thumbnail
  width: number;
  height: number;
  aiName?: string; // Generated by Gemini
}

export interface XhsPost {
  id: string;
  title: string;
  author: string;
  authorAvatar: string;
  images: XhsImage[];
  timestamp: number;
}

export interface ProcessingState {
  status: 'idle' | 'analyzing' | 'renaming' | 'downloading' | 'error' | 'success';
  message?: string;
  progress?: number;
  total?: number;
}